### ISSUE TITLE
Commands to read my credit card aren't working 

### ISSUE THREAD

**Issue by jjlofton7** [Ellerbach/ReadPaymentCreditCard#1]
is:issue is:open I added the code for ReadCreaditCardInfo.sln under directory : ~/pi-rfid $ 
but when i command my pi to read my credit card information it says command not found, am i using the wrong command?

**Comment by Ellerbach** [comment]
Can you please describe better what you are doing? The steps to reproduce exactly what you are doing are needed. So what do you exactly copy? Which command are you exactly runnig?

**Comment by jjlofton7** [comment]
once logged in I type *cd ~/pi-rfid *. After this type *sudo nano Write.py
*then click enter and I'm take to the screen that reads *"GNU nano 3.2* -*
Write.py"*

Next I paste the code in the file titled
"ReadCreaditCardInfo.sln"  from github.
After I save this I return to the command screen and I type command.

sudo python3 Read.py
But it says  command not found.

This also will not allow to to read my credit card. Did I copy and past the
wrong code? or am I not using the proper command to read a credit card?

**Comment by jjlofton7** [comment]
Once logged in I type:  cd ~/pi-rfid  

After this type: sudo nano Write.py  

Then click enter and I'm take to the screen that reads "GNU nano 3.2 - Write.py"

Next I paste the code in the file titled 
"ReadCreaditCardInfo.sln"  from github.
After I save this I return to the command screen and I type command: sudo python3 Read.py  
But it says "command not found".

This also will not allow to to read my credit card. Did I copy and past the wrong code? or am I not using the proper command to read a credit card?

**Comment by Ellerbach** [comment]
So this repository has nothing to do with Python. It's in .NET Core and C#.
Please read the main readme which will point you on the needed technologies:
https://github.com/Ellerbach/ReadPaymentCreditCard/blob/master/README.md
